# Generated by Django 4.1.1 on 2022-10-6 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='store_book_id',
            field=models.CharField(help_text='Book id from store', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
